<?php
/*
@file
* Include facebook login link from simple_fb_connect module 
* into drupal user login block
*/

/* Implementation of hook_form_alter */
function cool_login_form_alter(&$form, &$form_state, $form_id)
{
 if ($form_id == "user_login_block") {
  dpm($form);
  $form['facebook_login'] = array(
   '#markup' => '<div id="facebook-login" class="facebook-login">
 <p><a href="/user/simple-fb-connect">Login with Facebook</a></p>
<p id="facebook-login-or" class="facebook-login-or">Or</p>
</div>',
   '#weight' => - 10,
  );
  return $form;
 }
}

